# Pre-commit hooks configuration
repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: python tools/hooks/trailing_whitespace_fixer.py
        language: system
        types: [text]

      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: python tools/hooks/end_of_file_fixer.py
        language: system
        types: [text]

      - id: flake8
        name: flake8
        entry: python -m flake8
        language: system
        types: [python]
        exclude: '(^|/)(\.venv|venv|\.git|__pycache__|\.pytest_cache|\.github)/'

      - id: black
        name: black
        entry: python -m black --config=pyproject.toml
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: python -m isort --settings-path=pyproject.toml
        language: system
        types: [python]

      - id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        pass_filenames: false
        types: [python]
