[tool.black]

target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \venv
  | \.pytest_cache
  | \.github
  | __pycache__
  | _build
  | buck-out
  | build
  | dist
)
'''
skip-string-normalization = true
skip-magic-trailing-comma = true
check = false
line-length = 80

[tool.isort]
profile = "black"
line_length = 80
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = [".venv/*", ".pytest_cache/*", ".github/*", "__pycache__/*"]
