[tool.black]
line-length = 80
target-version = ['py39']
include = '\.pyi?$'
exclude = '/(\.git|\.hg|\.mypy_cache|\.tox|\.venv|_build|buck-out|build|dist)/'

[tool.isort]
profile = "black"
line_length = 80
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
case_sensitive = false
skip = [".git", "__pycache__", "venv", ".venv"]
known_first_party = ["utilities","adapters","command_libraries","scanner_gui"]
known_third_party = ["PyQt6","serial"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
